### ISSUE TITLE
Problem in Checkout

### ISSUE THREAD

**Issue by mirmibrahim** [craigchristenson/opencart-2checkout#3]
Hey i have recently configured 2checkout with opencart v1.5.6.4.
I have entered all details . The problem is when i checkout .it  shows credit card text box on my website. Whereas i want to checkout on external 2checkout website. Please help.

**Comment by craigchristenson** [comment]
I could be that you have direct checkout enabled and it is showing in the iframe. If you would like to redirect to 2Checkout to complete the order, you can disable direct checkout in the extension's configuration in opencart. If you are still having issues please provide a screen shot so I can troubleshoot further.
